In [1]:
import numpy as np
import math

In [2]:
a = np.array([1,2,3])
print(a)
# number of dimensions
print(a.ndim)

[1 2 3]
1


In [5]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
#print out length of each dimension
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [7]:
#type of the array (dype = data type)
b.dtype

dtype('int64')

In [8]:
c= np.array([2.2,4.3,2,3,4])
c.dtype.name

'float64'

In [9]:
c

array([2.2, 4.3, 2. , 3. , 4. ])

In [10]:
#numpy tries to give the best typoe of format to keep data homogenous
#you can create an array of filler values
d = np.zeros((2,3))
print(d)
e = np.ones((4,5))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [11]:
np.random.rand(2,3)

array([[0.89614286, 0.66680014, 0.73709683],
       [0.48549017, 0.57839982, 0.15934442]])

In [12]:
#arange = (first elem = starting, second elem = ending, third = difference in steps)
f= np.arange(10,50,5)
f

array([10, 15, 20, 25, 30, 35, 40, 45])

In [13]:
#in order to create a squernce of floats use linspace, 3rd argument is number of items you want to generate
np.linspace(0,2,15)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

In [14]:
#arithmetic operations occur element wise
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])
c= a-b
print(c)
d = a*b
print(d)

[ 9 18 27 36]
[ 10  40  90 160]


In [16]:
farenheit= np.array([0,-10,-5,-15,0])
celcius = (farenheit-31) *(5/9)
celcius

array([-17.22222222, -22.77777778, -20.        , -25.55555556,
       -17.22222222])

In [17]:
#you can apply an operation on the array and it will return a boolean array for every condition
celcius >-20

array([ True, False, False, False,  True])

In [18]:
celcius %2 == 0 

array([False, False,  True, False, False])

In [21]:
#numpy supports matrix manipulation
A= np.array([[1,1],[0,1]])
B= np.array([[2,0],[3,4]])
print(A*B) #this does element wise product
print(' ')
print(A@B) #does a matrix product

[[2 0]
 [0 4]]
 
[[5 4]
 [3 4]]


In [22]:
#Remember product of two matrices are only pausible if you the inner dimensions of the two matrices are the same
#when you are manipulating arrays of different types, the type of the resulting array will correspond to the more general of the two types (upcasting)

array1 = np.array([[1,2,3],[4,5,6]])
print(array1.dtype)
array2 = np.array([[2.3,4.2,44.3],[2.4,6.5,7.5]])
print(array2.dtype)

int64
float64


In [23]:
array3 = array1 + array2
print(array3)
print(array3.dtype)


[[ 3.3  6.2 47.3]
 [ 6.4 11.5 13.5]]
float64


In [24]:
#numpy arrays have built in functions as well
print(array3.sum())
print(array3.max())
print(array3.min())
print(array3.mean())

88.19999999999999
47.3
3.3
14.699999999999998


In [ ]:
b= np.arange(0,16,1).reshape(3,5)
print(b)