In [1]:
import numpy as np

In [2]:
data = np.random.randn(2,3)
data

array([[-0.71980669, -0.86894535,  1.081042  ],
       [ 0.5219842 , -2.21020007, -0.40414287]])

In [3]:
data*10

array([[ -7.19806692,  -8.68945354,  10.81042005],
       [  5.21984203, -22.10200067,  -4.04142873]])

In [5]:
data.dtype

dtype('float64')

In [6]:
data.shape

(2, 3)

In [9]:
#intitializing an nd array
# data1 = [6,4.5,23,4,1,"hi"] ndarry must be of homogeounus elemend types
data1 = [6,4.5,23,4,1]
arr = np.array(data1)
arr

array([ 6. ,  4.5, 23. ,  4. ,  1. ])

In [12]:
data2 = [[1,2,3,4],[3,4,5,6]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [13]:
arr2.ndim

2

In [14]:
arr2.shape

(2, 4)

In [16]:
arr2.dtype

dtype('int64')

In [17]:
arr.dtype

dtype('float64')

In [ ]:
np.arange(0,20)