In [2]:
import numpy as np
a = np.array([12.3,454.23,443,3])
a
#setting an np array

array([ 12.3 , 454.23, 443.  ,   3.  ])

In [4]:
b = np.array([
    [19.50, 13, 12, 11 ],
    [12.50, 10, 25, 14]])
b
b.shape
#returns the shape of the array 

(2, 4)

In [5]:
a+ b

array([[ 31.8 , 467.23, 455.  ,  14.  ],
       [ 24.8 , 464.23, 468.  ,  17.  ]])

In [6]:
np.linspace(0,20,2)

array([ 0., 20.])

In [7]:
x = np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])